#!/usr/bin/env python
# -*- coding: UTF-8 -*-
# coding=utf-8

"""
@author: Liyingjun
@contact: 694317828@qq.com
@software: pycharm
@file: oracle_test.py
@time: 2022/2/15 14:25
@desc: orcale测试建表语句
"""

oracle_data = """CREATE TABLE "ECSBPMDBT5"."TS_BPD_CFG" 
   (	"APP_NAME" VARCHAR2(128) NOT NULL ENABLE, 
	"APP_SHORTNAME" VARCHAR2(64), 
	"BPD_NAME" VARCHAR2(128), 
	"DOMAIN_LEVEL1" VARCHAR2(64), 
	"DOMAIN_LEVEL2" VARCHAR2(64), 
	"BPM_PLATFORM_VERSION" VARCHAR2(5), 
	"BPD_ABBREV_NAME" VARCHAR2(10), 
	"BTNO_CREATE_TYPE" VARCHAR2(2), 
	"BTNO_CLEAR_PERIOD" VARCHAR2(2), 
	"BTNO_CLEAR_LASTDATE" DATE, 
	"BPD_SYSTEM_TYPE" VARCHAR2(2), 
	"ENGINE_CODE" VARCHAR2(20), 
	"IS_DEFAULT" VARCHAR2(1), 
	"THIRD_PLATFORM" VARCHAR2(20), 
	"THIRD_PLATFORM_DOMAIN" VARCHAR2(20), 
	"ITCODE" VARCHAR2(64), 
	"CREATE_TIME" TIMESTAMP (6), 
	"CREATE_USER" VARCHAR2(64), 
	"OPERATION_TIME" TIMESTAMP (6), 
	"OPERATION_USER" VARCHAR2(64), 
	"IS_GRAY" VARCHAR2(1), 
	 CONSTRAINT "PK_TS_BPD_CFG" PRIMARY KEY ("APP_NAME", "BPD_NAME", "ENGINE_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSECSBPM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSECSBPM" ;

CREATE UNIQUE INDEX "ECSBPMDBT5"."PK_TS_BPD_CFG" ON "ECSBPMDBT5"."TS_BPD_CFG" ("APP_NAME", "BPD_NAME", "ENGINE_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSECSBPM" ;

COMMENT ON COLUMN ECSBPMDBT5.TS_BPD_CFG.APP_NAME IS '流程应用名';
COMMENT ON COLUMN ECSBPMDBT5.TS_BPD_CFG.APP_SHORTNAME IS '流程应用短名';
COMMENT ON COLUMN ECSBPMDBT5.TS_BPD_CFG.BPD_NAME IS '流程定义名称';
COMMENT ON COLUMN ECSBPMDBT5.TS_BPD_CFG.DOMAIN_LEVEL1 IS '所属业务域一级分类';
COMMENT ON COLUMN ECSBPMDBT5.TS_BPD_CFG.DOMAIN_LEVEL2 IS '所属业务域二级分类';
COMMENT ON COLUMN ECSBPMDBT5.TS_BPD_CFG.BPM_PLATFORM_VERSION IS '所应用的BPM平台版本号';
COMMENT ON COLUMN ECSBPMDBT5.TS_BPD_CFG.BPD_ABBREV_NAME IS '流程模板简称';
COMMENT ON COLUMN ECSBPMDBT5.TS_BPD_CFG.BTNO_CREATE_TYPE IS '单号生成规则';
COMMENT ON COLUMN ECSBPMDBT5.TS_BPD_CFG.BTNO_CLEAR_PERIOD IS '单号重置周期';
COMMENT ON COLUMN ECSBPMDBT5.TS_BPD_CFG.BTNO_CLEAR_LASTDATE IS '上一次重置时间';"""