# Generated by Django 3.2.10 on 2022-02-21 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DMPTbls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_name', models.CharField(max_length=32, verbose_name='数据库')),
                ('table_name', models.CharField(max_length=32, verbose_name='表名')),
                ('table_des', models.CharField(blank=True, max_length=255, null=True, verbose_name='表描述')),
            ],
            options={
                'db_table': 'DMPTbls',
            },
        ),
        migrations.CreateModel(
            name='FuncType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('func_type_name', models.CharField(max_length=64, verbose_name='功能类型')),
                ('func_type_des', models.CharField(default=None, max_length=255, verbose_name='功能类型描述')),
            ],
            options={
                'verbose_name': '我的功能',
                'verbose_name_plural': '我的功能',
                'db_table': 'MyFunc',
            },
        ),
        migrations.CreateModel(
            name='MyRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='规则名称')),
                ('alias', models.CharField(max_length=32, unique=True, verbose_name='规则别名')),
            ],
            options={
                'verbose_name': '我的角色',
                'verbose_name_plural': '我的角色',
                'db_table': 'MyRole',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=32, unique=True, verbose_name='ip')),
                ('name', models.CharField(default='未知', max_length=255, verbose_name='姓名')),
                ('count', models.IntegerField(default=0, verbose_name='访问次数')),
                ('is_admin', models.BooleanField(default=False, verbose_name='是否是管理员')),
                ('rule', models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='app.myrole')),
            ],
            options={
                'verbose_name': '我的用户',
                'verbose_name_plural': '我的用户',
                'db_table': 'MyUser',
            },
        ),
        migrations.CreateModel(
            name='UrlManage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('func_name', models.CharField(max_length=255, unique=True, verbose_name='功能')),
                ('func_url', models.CharField(max_length=64, unique=True, verbose_name='地址')),
                ('func_url_name', models.CharField(default='', max_length=64, verbose_name='地址别名')),
                ('func_des', models.CharField(default=None, max_length=255, verbose_name='功能描述')),
                ('func_label', models.IntegerField(choices=[(1, '正常使用'), (2, '开发中'), (3, '开发者使用'), (4, '特定用户使用')], default=1, verbose_name='状态')),
                ('auth_role', models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='app.myrole', verbose_name='访问角色权限')),
                ('func_type', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='app.functype', verbose_name='功能类型')),
            ],
            options={
                'verbose_name': '我的地址',
                'verbose_name_plural': '我的地址',
                'db_table': 'MyUrl',
            },
        ),
    ]
