# Generated by Django 3.2.10 on 2022-02-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='functype',
            name='shown_index',
            field=models.BooleanField(default=True, verbose_name='是否展示在主页'),
        ),
    ]
