# Generated by Django 3.2.10 on 2022-04-11 01:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_functype_shown_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlmanage',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='urlmanage',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
