# Generated by Django 3.2.10 on 2022-05-09 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220411_0947'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='functype',
            table='FuncType',
        ),
    ]
