# Generated by Django 3.2.10 on 2022-05-09 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_functype_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UrlManage',
            new_name='Url',
        ),
        migrations.AlterModelTable(
            name='url',
            table='Url',
        ),
    ]
