# Generated by Django 3.2.10 on 2022-05-09 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20220509_1604'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='IP',
        ),
        migrations.RenameModel(
            old_name='MyRole',
            new_name='Role',
        ),
        migrations.AlterModelTable(
            name='ip',
            table='IP',
        ),
        migrations.AlterModelTable(
            name='role',
            table='Role',
        ),
    ]
