# Generated by Django 3.2.10 on 2022-05-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20220509_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
            ],
            options={
                'verbose_name': '我的用户',
                'verbose_name_plural': '我的用户',
                'db_table': 'my_table_user',
            },
        ),
        migrations.AlterModelOptions(
            name='ip',
            options={'verbose_name': '我的IP', 'verbose_name_plural': '我的IP'},
        ),
        migrations.AlterModelTable(
            name='ip',
            table='my_table_ip',
        ),
    ]
