# Generated by Django 3.2.10 on 2022-05-09 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20220509_1608'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='functype',
            table='my_table_functype',
        ),
        migrations.AlterModelTable(
            name='role',
            table='my_table_role',
        ),
        migrations.AlterModelTable(
            name='url',
            table='my_table_url',
        ),
    ]
