# Generated by Django 3.2.10 on 2022-05-09 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20220509_1609'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dmptbls',
            table='my_table_DMPTbls',
        ),
    ]
