# Generated by Django 3.2.10 on 2022-05-09 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_dmptbls_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ip',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='是否是管理员'),
        ),
    ]
