# Generated by Django 3.2.10 on 2022-05-09 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20220509_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ip',
            name='rule',
        ),
        migrations.AddField(
            model_name='user',
            name='rule',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.SET_DEFAULT, to='app.role'),
        ),
    ]
