# Generated by Django 3.2.10 on 2022-05-09 08:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20220509_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='ip',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ip',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='最后一次访问时间'),
        ),
    ]
